export const SliderData = [
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/c1642e659f5-BeautyLauch-SB-June22.jpg",
  },
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/769d35ac08e-BachatDay-CB-19July-min.jpg?dim=700x0&dpr=1&q=100",
  },
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/3bdb0db12e1-ABZORB-JUL.jpg",
  },
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/33ce2b5ba8b-Friends-CB-May22.jpg",
  },
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/c4d259a9077-OneTouchSPS-CB-July22.png",
  },
  {
    image: "https://cms-contents.pharmeasy.in/banner/b1cd3f940f5-Evion-CB.jpg",
  },
  {
    image:
      "https://cms-contents.pharmeasy.in/banner/a86af72f350-Huggies-CB-May22.jpg",
  },
];
